### ISSUE TITLE
Create scene template for levels

### ISSUE THREAD

**Issue by g-lilian** [ShengXue97/Memory-Lanes#26]
Rn whenever we modify the locations of the load/save/reload buttons, we have to manually shift them for all levels :O 
We should create a template to quickly do this. Is there something like a prefab for scenes? Preferably the linked buttons should all shift automatically in all scenes, whenever we update the template.

https://docs.unity3d.com/Packages/com.unity.scene-template@1.0/manual/index.html

**Comment by PotatoCombat** [comment]
Yeah that seems troublesome. We can combine this with #21.
